### ISSUE TITLE
Inconsistent installation instructions

### ISSUE THREAD

**Issue by maelle** [noamross/redoc#31]
The README refers to using remotes/devtools but https://noamross.github.io/redoc/articles/mixed-workflows-with-redoc.html#installation refers to another method.

**Comment by maelle** [comment]
For info there's a method to re-use parts of the README/vignettes https://www.garrickadenbuie.com/blog/dry-vignette-and-readme/

**Comment by noamross** [comment]
I've fixed this for now but the method above for reusing docs, so re-opening the issue.
