### ISSUE TITLE
Cross-references using bookdown::word_document2

### ISSUE THREAD

**Issue by jooyoungseo** [noamross/redoc#52]
As far as I know, currently `redoc::redoc` utilizes `rmarkdown::word_document` under the hood. Would you mind replacing it with `bookdown::word_document2` to allow users to cross-reference tables, figures, etc.?

**Comment by noamross** [comment]
Thanks! This is on the roadmap (#34), but it's more complicated than that because we need to set up capturing the information in those cross-references and make the post-processing steps compatible.
